<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Georgesnotes - Programming</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/blog/">
    <link href="../../../style/default.css" rel="stylesheet" type="text/css">
    <link href="../../../style/prog.css" rel="stylesheet" type="text/css">
    <link href="../../../style/responsive.css" rel="stylesheet" type="text/css">
</head>

<body>
    <!-- Navbar -->
    <div class="navbar_div">
        <?php include '../../component/navbar_stories.php'; ?>
    </div>
    <div class="mainbody_div">
        <!-- Page title -->
        <div class="page_title">
            <h1>Programming</h1>
        </div>
        <div class="space"></div>
        <!-- Stories -->
        <div class="stories">
            <!-- Storie1 -->
            <div class="storie">

                <div class="stories_article_card">
                    <div class="card">
                        <a href="/frontend/view/page/stories/programming.php">
                            <img src="/frontend/assets/images/datastruct.jpg" class="card-img-top" alt="image_post">
                        </a>
                    </div>
                </div>


                <div class="stories_article_description">
                    <h2>Data structures</h2>
                    <h5>Static data structures: Exploring the Benefits and Applications of Static Data Structures.</h5>
                    <p class="post_author_datum">By <b class="post_author">Georges Miaka</b>
                        <spam class="post_datum">June 13, 2023</spam>
                    </p>
                    <p class="stories_article_description_text article_text">
                        Static data structures are data structures whose size is predetermined at compile
                        time and cannot be changed during program execution.
                        In other words, once the data structure is created, its size cannot be changed.
                        Common examples of static data structures include arrays, static linked lists,
                        and trees with fixed maximum depth. Arrays are a collection of of elements of
                        the same type, arranged in a contiguous block of memory, and accessed by an index.
                        The size of an array is determined at compile time, and each element can be accessed in constant time.
                        Static linked lists are similar to arrays in hat they consist of a collection of elements of the same
                        type, but they are not arranged in a contiguous block of memory. Instead, each element contains a pointer
                        to the next…
                        <a class="link_article_description" href="#">See more</a>
                    </p>
                </div>
            </div>
            <!-- Space & divider -->
            <div class="space"></div>
            <hr class="divider">
            <div class="space"></div>
            <!-- Storie2 -->
            <div class="storie">

                <div class="stories_article_card">
                    <div class="card">
                        <a href="/frontend/view/page/stories/programming.php">
                            <img src="/frontend/assets/images/ml.jpg" class="card-img-top" alt="image_post">
                        </a>
                    </div>
                </div>


                <div class="stories_article_description">
                    <h2>Machine Learning</h2>
                    <h5>ML: A Comprehensive Exploration of Machine Learning's Algorithms.</h5>
                    <p class="post_author_datum">By <b class="post_author">Georges Miaka</b>
                        <spam class="post_datum">June 13, 2023</spam>
                    </p>
                    <p class="stories_article_description_text article_text">
                        Machine learning has become increasingly important in recent years, as the volume of data being 
                        generated by businesses, governments, and individuals has grown exponentially. Machine learning 
                        algorithms are now used in a wide range of applications, from image recognition and natural language 
                        processing to fraud detection and recommendation systems.
                        There are many different types of machine learning algorithms, including…
                        <a class="#">See more</a>
                    </p>
                </div>
            </div>

        </div>
        <!-- Space & divider -->
        <div class="space"></div>
        <hr class="divider divider_footer">
        <div class="space"></div>
        <!-- Footer -->
        <div><?php include '../../component/footer.php' ?></div>


    </div>
    <!-- space -->
    <div class="space_footer"></div>
    <!-- Navbar_bootom -->
    <div>
        <?php include '../../component/navbar_bottom_stories.php'; ?>
    </div>
</body>

</html>